### ISSUE TITLE
I lost brain cells trying to figure out setup as a web newb

### ISSUE THREAD

**Issue by maikirakiwi** [tsunyoku/Katagami#1]
Whatever, need more elaboration on the installation guide. Just copy and paste from here and commit the changes. You are welcome.

* Note that I'm writing this after 30 hours of not sleeping, correct some of the wording if you will.

Below are installation instructions if you only plan to host mainly Katagami on your Ubuntu Linux instance.

Linux (Ubuntu 18.04 LTS):
```bash
# Make sure you install Python3.9-dev via ppa first 
sudo apt install mysql-server
sudo mysql_secure_installation
# Follow MySQL installation instructions. Create a user with sufficient privileges and write down both username & pw.
# Make sure ufw or similar firewall programs are either off or has rules updated for v4/v6.

git clone https://github.com/tsunyoku/Katagami.git
# 
mv ext/requirements.txt requirements.txt
python3.9 -m pip install -r requirements.txt && rm -rf requirements.txt
mv ext/config.sample.py config.py # Edit your config.py file with a text editor of your choice.
cp ext/nginx.conf /etc/nginx/nginx.conf  # Open /etc/nginx/nginx.conf with a text editor of your choice.
# Make a couple lines of space before the first server { line and change configuration to something like the following: 
# events{} 
# http{
# server{
# ...
# }
# }
# Also make sure proxy_pass for the second server { } is set to your chosen port.
# make a copy of the file, delete the entire second server { } with the listen 443 whatever.  (Maybe the third one as well if you don't plan on using pma)
# Follow the instructions here to get an auto-renewing SSL cert (https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx)
# Edit the /etc/nginx/nginx.conf, remember the ssl_certificate and ssl_certificate_key domain (the part after /live/)
# cp ext/nginx.conf /etc/nginx/nginx.conf again, this time you're going to do the same steps again like above after cp.
# Edit the line ssl_certificate and ssl_certificate_key to what it looked like before you did this second cp.
# Save the nginx.conf, and sudo nginx -s reload.
# Now double check the config.py in Katagami's directory has both correct credentials for MySQL and the correct port for proxy_pass.
```

**Comment by maikirakiwi** [comment]
Also there's multiple indentation errors in main.py

**Comment by atteure** [comment]
ill be dead honest we completely forgot about this whole project until i read through my github notifications
sure i'll commit this in a bit but i'll include it in the next big commit

**Comment by tsunyoku** [comment]
Some of these nginx comments are a bit, eh... Katagami was made to be dev friendly and not user friendly, yes we will provide command instructions and an example nginx config but this level of depth for an nginx config is more noob-proof than dev-proof, and quite cluttering. Will provide more clarity in the instrutions but not to this depth, basically. As for the indentation errors, they'll get fixed too. This project kind of deid due to my focus on Asahi but in the future it'll get revived.
